### ISSUE TITLE
spdk_dd error while prepping

### ISSUE THREAD

**Issue by pykello** [ubicloud/ubicloud#1931]
```
[2024-09-12 20:32:50.053673] app.c: 387:app_setup_env: *ERROR*: Unable to initialize SPDK env
[2024-09-12 20:32:50.053681] spdk_dd.c:1516:main: *ERROR*: Error occurred while performing copy
[2024-09-12 20:32:50.053703] app.c: 597:unclaim_cpu_cores: *ERROR*: Failed to unlink lock fd for core 0, errno: 2
	from /home/rhizome/host/lib/storage_volume.rb:207:in `encrypted_image_copy'
	from /home/rhizome/host/lib/storage_volume.rb:219:in `create_ubi_writespace'
	from /home/rhizome/host/lib/storage_volume.rb:56:in `prep'
	from /home/rhizome/host/lib/vm_setup.rb:503:in `block in storage'
	from /home/rhizome/host/lib/vm_setup.rb:499:in `map'
	from /home/rhizome/host/lib/vm_setup.rb:499:in `storage'
	from /home/rhizome/host/lib/vm_setup.rb:52:in `block in prep'
```

**Comment by pykello** [comment]
We're moving away from spdk. So, closing this.
