### ISSUE TITLE
Make vm_setup.rb idempotent

### ISSUE THREAD

**Issue by pykello** [ubicloud/ubicloud#483]
So a failed vm setup is retriable.

Following is an example of failures we can get but there might be more:

```
mkdosfs: file /vm/vmv6cz0z/cloudinit.img already exists
	from /home/rhizome/lib/vm_setup.rb:330:in `cloudinit'
	from /home/rhizome/lib/vm_setup.rb:47:in `prep'
	from bin/prepvm.rb:89:in `<main>'
```

**Comment by ozgune** [comment]
Hi @furkansahin, @fdr - I think we fixed this. If we did, can you close this issue?
