### ISSUE TITLE
Destroying vm stuck if vm deleted before vhost creation

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#505]
```
---STDOUT---
request:
{
  "ctrlr": "vmyca6yj_0",
  "method": "vhost_delete_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "No such device"
}


---STDERR---
        from /home/rhizome/lib/vm_setup.rb:124:in `block in purge_storage'
        from /home/rhizome/lib/vm_setup.rb:118:in `each'
        from /home/rhizome/lib/vm_setup.rb:118:in `purge_storage'
        from /home/rhizome/lib/vm_setup.rb:106:in `purge'
        from bin/deletevm.rb:12:in `<main>'

```

**Comment by pykello** [comment]
Fixed in https://github.com/ubicloud/ubicloud/pull/784
