### ISSUE TITLE
Invalid MAC issue while provisioning a vm

### ISSUE THREAD

**Issue by enescakir** [ubicloud/ubicloud#745]
We encountered this issue a few times at production. The vm stuck at `wait_sshable` because the respirate can't connect to the vm via IPv4. `cat /vm/VM_NAME/serial.log` has this exception
```
[    4.416703] cloud-init[462]: 2023-10-16 10:20:24,707 - util.py[WARNING]: failed stage init-local
[    4.422362] cloud-init[462]: failed run of stage init-local
[    4.423244] cloud-init[462]: ------------------------------------------------------------
[    4.424499] cloud-init[462]: Traceback (most recent call last):
[    4.425442] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 766, in status_wrapper
[    4.426706] cloud-init[462]:     ret = functor(name, args)
[    4.427514] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 432, in main_init
[    4.428784] cloud-init[462]:     init.apply_network_config(bring_up=bring_up_interfaces)
[    4.429840] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 939, in apply_network_config
[    4.431105] cloud-init[462]:     return self.distro.apply_network_config(
[    4.432065] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 281, in apply_network_config
[    4.433386] cloud-init[462]:     self._write_network_state(network_state, renderer)
[    4.434374] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/distros/debian.py", line 142, in _write_network_state
[    4.435694] cloud-init[462]:     return super()._write_network_state(*args, **kwargs)
[    4.436714] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 169, in _write_network_state
[    4.438036] cloud-init[462]:     renderer.render_network_state(network_state)
[    4.438986] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/net/netplan.py", line 310, in render_network_state
[    4.440309] cloud-init[462]:     self._netplan_generate(run=self._postcmds, same_content=same_content)
[    4.441437] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/net/netplan.py", line 323, in _netplan_generate
[    4.442701] cloud-init[462]:     subp.subp(self.NETPLAN_GENERATE, capture=True)
[    4.443661] cloud-init[462]:   File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 335, in subp
[    4.444810] cloud-init[462]:     raise ProcessExecutionError(
[    4.445658] cloud-init[462]: cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
[    4.446790] cloud-init[462]: Command: ['netplan', 'generate']
[    4.447640] cloud-init[462]: Exit code: 1
[    4.448305] cloud-init[462]: Reason: -
[    4.448923] cloud-init[462]: Stdout:
[    4.449504] cloud-init[462]: Stderr: /etc/netplan/50-cloud-init.yaml:12:29: Error in network definition: Invalid MAC address '40626667100', must be XX:XX:XX:XX:XX:XX or XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX
[    4.451490] cloud-init[462]:                         macaddress: 40626667100
[    4.452459] cloud-init[462]:                                     ^
[    4.453344] cloud-init[462]: ------------------------------------------------------------
[FAILED] Failed to start Initial cloud-init job (pre-networking).
See 'systemctl status cloud-init-local.service' for details.
```

`sudo systemctl status VM_NAME-dnsmasq.service` shows only IPv6 addresses not IPv4.

`sudo systemctl status VM_NAME.service` shows the vm is started.
```
● VM_NAME.service - VM_NAME
     Loaded: loaded (/etc/systemd/system/VM_NAME; static)
     Active: active (running) since Mon 2023-10-16 12:20:17 CEST; 17min ago
   Main PID: 1556174 (cloud-hyperviso)
      Tasks: 12 (limit: 4230)
     Memory: 6.9M
        CPU: 18.746s
     CGroup: /system.slice/VM_NAME.service
             └─1556174 /opt/cloud-hypervisor/v31.0/cloud-hypervisor --api-socket path=/vm/VM_NAME/ch-api.sock --kernel /opt/fw/edk2-stable202302/x64/CLOUDHV.fd --disk vhost_user=true,socket=/var/storage/VM_NAME/0/vhost.sock,num_queues=1,queue_size=256 --disk path=/vm/VM_NAME/clo>

Oct 16 12:20:17 Ubuntu-2204-jammy-amd64-base systemd[1]: Starting VM_NAME...
Oct 16 12:20:17 Ubuntu-2204-jammy-amd64-base systemd[1]: Started VM_NAME.
```

**Comment by fdr** [comment]
Closed by 59e81d20ad6c7764b7912268ae4b88c58fcc178d
