### ISSUE TITLE
Deleting vhost controller when purging the VM failed

### ISSUE THREAD

**Issue by pykello** [ubicloud/ubicloud#853]
This is probably a race condition and `systemctl stop vm12345` takes time.

```
/home/rhizome/host/lib/spdk_rpc.rb:18:in `rescue in rpc_call': Device or resource busy (SpdkRpcError)
	from /home/rhizome/host/lib/spdk_rpc.rb:15:in `rpc_call'
	from /home/rhizome/host/lib/spdk_rpc.rb:61:in `vhost_delete_controller'
	from /home/rhizome/host/lib/storage_volume.rb:73:in `purge_spdk_artifacts'
	from /home/rhizome/host/lib/vm_setup.rb:113:in `block in purge_storage'
	from /home/rhizome/host/lib/vm_setup.rb:111:in `each'
	from /home/rhizome/host/lib/vm_setup.rb:111:in `purge_storage'
	from /home/rhizome/host/lib/vm_setup.rb:96:in `purge'
	from host/bin/deletevm.rb:12:in `<main>'
/home/rhizome/host/lib/json_rpc_client.rb:39:in `call': Device or resource busy (JsonRpcError)
	from /home/rhizome/host/lib/spdk_rpc.rb:16:in `rpc_call'
	from /home/rhizome/host/lib/spdk_rpc.rb:61:in `vhost_delete_controller'
	from /home/rhizome/host/lib/storage_volume.rb:73:in `purge_spdk_artifacts'
	from /home/rhizome/host/lib/vm_setup.rb:113:in `block in purge_storage'
	from /home/rhizome/host/lib/vm_setup.rb:111:in `each'
	from /home/rhizome/host/lib/vm_setup.rb:111:in `purge_storage'
	from /home/rhizome/host/lib/vm_setup.rb:96:in `purge'
	from host/bin/deletevm.rb:12:in `<main>'
```

**Comment by pykello** [comment]
We're moving away from SPDK. So, closing this.
