### ISSUE TITLE
JSON-RPC timeouts

### ISSUE THREAD

**Issue by pykello** [ubicloud/ubicloud#894]
We had some failures with the following error. It succeeded on a retry:

```
/home/rhizome/host/lib/spdk_rpc.rb:111:in `read_response': The request timed out after 5 seconds. (RuntimeError)
	from /home/rhizome/host/lib/spdk_rpc.rb:88:in `call'
	from /home/rhizome/host/lib/spdk_rpc.rb:19:in `bdev_aio_create'
	from /home/rhizome/host/lib/storage_volume.rb:228:in `setup_spdk_bdev'
	from /home/rhizome/host/lib/storage_volume.rb:56:in `start'
	from /home/rhizome/host/lib/vm_setup.rb:443:in `block in storage'
	from /home/rhizome/host/lib/vm_setup.rb:438:in `map'
	from /home/rhizome/host/lib/vm_setup.rb:438:in `storage'
	from /home/rhizome/host/lib/vm_setup.rb:50:in `prep'
	from host/bin/prepvm.rb:90:in `<main>' 
```

**Comment by pykello** [comment]
We're moving away from SPDK. So, closing this.
